import { createApp } from 'vue';
import { createPinia } from 'pinia';
import { createDiscreteApi } from 'naive-ui';
import App from './App.vue';
import router from './router';
import './styles/global.css';
const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
app.use(router);
const { message } = createDiscreteApi(['message']);
app.config.globalProperties.$message = message;
app.mount('#app');
